---
pipeline:
  fetch:
    unit_test:
      deploy
steps:
  fetch:
    script: scripts/tar_application.sh
    output_artifacts:
      - scm_artifact.tar
  unit_test:
    input_artifacts:
      - scm_artifact.tar
    script: scripts/unit_test.sh
    output_artifacts:
      - scm_artifact.tar
  deploy:
    input_artifacts:
      - scm_artifact.tar
    script: scripts/deploy_application.sh
